extends:
  - airbnb
  - plugin:flowtype/recommended
env:
  browser: true
  node: true
plugins:
  - flowtype
rules:
  react/jsx-filename-extension: 0
  react/no-array-index-key: 0
  global-require: 0
  import/no-dynamic-require: 0
